name: Update and Run Application on VM

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  update-and-run:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
          HOST: ${{ secrets.VM_HOST }}                 
          USER: ${{ secrets.VM_USER }}                 
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Pull Latest Changes and Manage Processes
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER@$HOST" << 'EOF'
            # Pull the latest code
            cd /home/ec2-user/ai-avatar  
            git pull origin main  
            
            # Kill existing processes listening on port 3000
            PIDs=$(sudo netstat -nlp | grep 3000 | awk '{print $7}' | cut -d'/' -f1)
            if [ -n "$PIDs" ]; then
              echo "Killing processes with PIDs: $PIDs"
              sudo kill -9 $PIDs
            else
              echo "No processes found listening on port 3000"
            fi
            
            # Install dependencies and run the application
            npm run build  
            
            # Start the application in a detached screen session
            screen -dmS myapp npm run dev
          EOF

